### ISSUE TITLE
UMLet diagram type not supported

### ISSUE THREAD

**Issue by jamesbooker** [sphinx-contrib/kroki#1]
One of the diagram types supported by the Kroki service (UMLet) is not supported by the extension

**Comment by hason** [comment]
@jamesbooker Thanks! Fixed in 1.1.0.

**Comment by jamesbooker** [comment]
Thank you! I tried to fix it myself but couldn't figure out the architecture. Maybe you could create a small 'how to add a library' readme with some pointers for future contributions?
