### ISSUE TITLE
Kroki not supported in Latex builder

### ISSUE THREAD

**Issue by jamesbooker** [sphinx-contrib/kroki#2]
Unable to build latex documents when kroki directives are present, even with the sphinxcontrib-svg2pdfconverter extension installed.

writing... failed

Exception occurred:
  File "c:\<snip>\venv\lib\site-packages\sphinx\writers\latex.py", line 2044, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: kroki

**Comment by fkolpakov** [comment]
the same problem.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/gtrd/envs/latest/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2042, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: kroki

**Comment by hason** [comment]
@jamesbooker @fkolpakov This issue should be resolved in https://github.com/sphinx-contrib/kroki/releases/tag/1.2.1

**Comment by jamesbooker** [comment]
> 
> 
> @jamesbooker @fkolpakov This issue should be resolved in https://github.com/sphinx-contrib/kroki/releases/tag/1.2.1

Thanks, I'll check it out
